### ISSUE TITLE
Add laravel-gelf-logger to Graylog Marketplace

### ISSUE THREAD

**Issue by joschi** [hedii/laravel-gelf-logger#1]
Thanks for writing this library!

It would be great if you added this project to the Graylog Marketplace, so that other users can find it. 😄 

* https://marketplace.graylog.org/
* http://docs.graylog.org/en/2.3/pages/marketplace.html

**Comment by hedii** [comment]
Done :)

https://marketplace.graylog.org/addons/873f7f47-417f-44ba-b06f-dbb1a6fdca81
