### ISSUE TITLE
'name' field is not sent in 'facility' field.

### ISSUE THREAD

**Issue by andho** [hedii/laravel-gelf-logger#14]
Even when 'name' field is set in the logging configuration, 'facility' field has 'local' (app.env value) when it's sent to graylog2.

Using laravel/framework:^6.2 and hedii/laravel-gelf-logger:^4.0, with a completely new laravel project.

**Comment by hedii** [comment]
Please paste your full logging.php config.
I use this package on multiple projects, and i do have the right facility set correctly.

**Comment by andho** [comment]
[logging.php](https://gist.github.com/andho/062cdabb3ebc2c4101e83672bf62925d).

If I set the APP_ENV to something else, it's reflected correctly in graylog2.

**Comment by andho** [comment]
There is no issue when using 'gelf' channel directly with `LOG_CHANNEL=gelf`, but when using `LOG_CHANNEL=stack`, this issue occurs, even if the only channel in the stack is `gelf`.

Using the `gelf` channel directly also works correctly, so I assume this is an issue with the `stack` driver.

Will file a bug report there.

**Comment by genrmiranda** [comment]
I have this issue as well gelf does not work on stack

**Comment by andho** [comment]
@genrmiranda I ended up not reporting this as a bug, as it seems this is the intended behavior of the stack driver. I just resolved to setting the `name` field in the stack driver directly, which seems to work, If I recall correctly. If it doesn't work let me know, I'll have to dig up the code and double check.

**Comment by ElectroBuddha** [comment]
I can confirm that following 'stack' setup is correctly setting 'facility' field when logging to 'stack' channel:
```
'channels' => [
      'stack' => [
          'driver' => 'stack',
          'channels' => ['single', 'gelf'],
          'name' => 'some facility value'
      ],
      ...
```

**Comment by romandots** [comment]
I'm having the same issue with stack driver. 
Log sent via channel 'gelf' has the facility defined in the name config. Logs sent to stack has the default value (which is app.env).

**Comment by hedii** [comment]
@romandots I don't see any issue with that. Stack is configured by laravel not by gelf package, it uses its own name.

If you want to use stack and change the name, look at the comment just before yours (I have not tested it myself)

**Comment by romandots** [comment]
> @romandots I don't see any issue with that. Stack is configured by laravel not by gelf package, it uses its own name.
> 
> If you want to use stack and change the name, look at the comment just before yours (I have not tested it myself)

Yes indeed, you are right. The solution above is working, so it's probably not an issue.
