### ISSUE TITLE
which version is suitalbe fo laravel 6.x ?

### ISSUE THREAD

**Issue by ibrahimMahfuz** [hedii/laravel-gelf-logger#23]
is there any version sutable for laravel 6.x, because i couldn't find it on readme, thank you

**Comment by hedii** [comment]
Hi,

You can use `^4.1`

Changelog on the releases page: https://github.com/hedii/laravel-gelf-logger/releases

**Comment by ibrahimMahfuz** [comment]
thank you

**Comment by ibrahimMahfuz** [comment]
> Hi,
> 
> You can use `^4.1`
> 
> Changelog on the releases page: https://github.com/hedii/laravel-gelf-logger/releases

thank you
