### ISSUE TITLE
Is this package is available for Laravel 8 ? 

### ISSUE THREAD

**Issue by chococrypto** [hedii/laravel-gelf-logger#26]
It would be nice to know for which version of Laravel this package is available. 

For example by adding this to the Readme :

| **Laravel**  |  **laravel-gelf-logger** |
|---|---|
| 5.6  | ^3.0  |
| 5.7  | ^4.0  |
| 5.8  | ^5.0  |
| 6.0  | ^6.0  |
| 7.0  | ^7.0 |
| 8.0  | ^8.0 |

**Comment by hedii** [comment]
yes, would you like to make a PR?

**Comment by chococrypto** [comment]
yes I can but I would like to know on which version the package is compatible

**Comment by hedii** [comment]
Each version has a composer.json file with versioned dependencies, there is also the change log in the releases page.
