### ISSUE TITLE
Unable to send logs to Graylog

### ISSUE THREAD

**Issue by dannielmags** [hedii/laravel-gelf-logger#30]
I'm still unable to send logs to Graylog with my Setup, please help :'( 

logging.php
```
    'channels' => [
        'stack' => [
            'driver' => 'stack',
            'channels' => ['single', 'gelf'],
            'ignore_exceptions' => false,
        ],

        'gelf' => [
            'driver' => 'custom',
            'via' => \Hedii\LaravelGelfLogger\GelfLoggerFactory::class,
            'level' => env('LOG_LEVEL', 'debug'),
            'name' => 'my-custom-name',
            'transport' => 'http',
            'host' => '0.0.0.0',
            'port' => 12201,
        ]
```
Controller to send Log
```
        $request = new Request([
            'version' => '1.1',
            'host' => '127.0.0.1',
            'short_message' => 'mama mo skkkrt',
            'level' => 1,
        ]);
 
        Log::channel('gelf')->debug('s', $request->all());
```
Thanks in advance :D

**Comment by hedii** [comment]
Your graylog server is accessible at `http://0.0.0.0:12201/gelf` without being logged in to graylog?

**Comment by hedii** [comment]
Try sending a message from a terminal:

```bash
curl -X POST -H 'Content-Type: application/json' -d '{ "version": "1.1", "host": "example.org", "short_message": "A short message", "level": 5, "_some_info": "foo" }' 0.0.0.0:12201/gelf
```

Go to your graylog instance, and check if your configured http input has received the message.

It should look like this (if that's not the case, you have misconfigured graylog, and i cannot help you with that):

<img width="1115" alt="Capture d’écran 2021-03-25 à 10 51 28" src="https://user-images.githubusercontent.com/5358048/112453721-42114a80-8d58-11eb-8cab-89c9f6695fe3.png">

<img width="1113" alt="Capture d’écran 2021-03-25 à 10 53 19" src="https://user-images.githubusercontent.com/5358048/112453965-800e6e80-8d58-11eb-95c8-91be97ab256c.png">

**Comment by dannielmags** [comment]
Thanks for the help @hedii  :D we just solve the problem, The gelf is not working with LaravelSail. We just tried it using a clean project pulling from a composer, and it works smoothly. :D Thank you
