### ISSUE TITLE
Unicode problem

### ISSUE THREAD

**Issue by GeoPvN** [hedii/laravel-gelf-logger#31]
![image](https://user-images.githubusercontent.com/11226226/131493948-b190bd42-c3a3-4dd3-85c8-b4a447fb1be3.png)

 'stack' => [
            'driver' => 'stack',
            'channels' => ['single', 'gelf'],
        ],

'gelf' => [
            'driver' => 'custom',
            'via' => \Hedii\LaravelGelfLogger\GelfLoggerFactory::class,
            'processors' => [
                \Hedii\LaravelGelfLogger\Processors\NullStringProcessor::class,
                // another processor...
            ],
            'level' => 'debug',
            'name' => 'bms-admin',
            'system_name' => null,
            'transport' => 'udp',
            'host' => env('GREY_LOGGER_IP_COM'),
            'port' => env('GREY_LOGGER_PORT_COM'),
            'path' => null,
            'max_length' => null,
            'context_prefix' => null,
            'extra_prefix' => null,
        ],
        
       Do you have any idea to fix this?

**Comment by hedii** [comment]
No idea. The message is defined in your code anywhere you are sending logs, not in the configuration. Search your code to understand why there is a character encoding issue.
