### ISSUE TITLE
udp and openvpn

### ISSUE THREAD

**Issue by amarmain** [hedii/laravel-gelf-logger#45]
Laravel version: 10.13.0
hedii/laravel-gelf-logger version: 8.0.1

Can you add the possibility to set the third parameter of UdpTransport class?

`    public function __construct(
        string $host = self::DEFAULT_HOST,
        int $port = self::DEFAULT_PORT,
        private int $chunkSize = self::CHUNK_SIZE_WAN
    )`

If the message is too long (backtrace), the message is not send to my graylog server.

Here are some explanation about the MTU issue with OpenVpn:

https://github.com/bzikarsky/gelf-php/issues/117#issuecomment-518946816

If I override this line from GelfLoggerFactory.php file, I can receive the message to my graylog server:

`    default => new UdpTransport($host, $port, 1200),`

instead of

`    default => new UdpTransport($host, $port),`

**Comment by hedii** [comment]
Hi, yes i will add it as soon as i have time to write it. Thanks!

**Comment by amarmain** [comment]
Thanks for your help!
