### ISSUE TITLE
Stuck for 8s if the remote service is unavailable

### ISSUE THREAD

**Issue by Webinx** [hedii/laravel-gelf-logger#46]
Hello, is there a built-in way to handle async requests or set a custom timeout? Currently, when the remote service is unavailable, my app gets stuck for 8 seconds for each log request.

**Comment by hedii** [comment]
Hi, what you want is to use udp transport (check the readme)

**Comment by Webinx** [comment]
Yes, I am already using it. In fact, I am using the exact same configuration as in the readme.

**Comment by hedii** [comment]
It is not possible that your app is getting stuck with udp transport. Please share your full logging config
