### ISSUE TITLE
Trait 'Illuminate\Log\ParsesLogConfiguration' not found

### ISSUE THREAD

**Issue by tumichnix** [hedii/laravel-gelf-logger#5]
Hi,

I try to use your package with Laravel 5.6.
If I call "`Log:channel('gelf')->:critical('Foobar');`" I am getting "`Symfony\Component\Debug\Exception\FatalErrorException  : Trait 'Illuminate\Log\ParsesLogConfiguration' not found`".

Stacktrace:
```
  1   Symfony\Component\Debug\Exception\FatalErrorException::__construct()
      /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:137

  2   Illuminate\Foundation\Bootstrap\HandleExceptions::fatalExceptionFromError()
      /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:123
```

**Comment by hedii** [comment]
> Log:channel('gelf')->:critical('Foobar');

You have a typo in your snippet: semicolon before "critical"

**Comment by hedii** [comment]
Thanks for reporting, please run composer update.
